gg.web/Models/GroupViewModel.cs
namespace gg.web.Models
{
    public class GroupViewModel
    {
        public long Id { get; set; }
        public string Name { get; set; }
    }
}

gg.web/Controllers/GroupsController.cs
using gg.core;
using gg.web.Mappings;
using gg.web.Models;
using Microsoft.AspNetCore.Mvc;

namespace gg.web.Controllers
{
    [Route("groups")]
    public class GroupsController : Controller
    {
        private readonly IGroupsService _groupsService;

        public GroupsController(IGroupsService groupsService)
        {
            _groupsService = groupsService;
        }

        [HttpGet]
        [Route("")]
        public IActionResult Index()
        {
            return View(_groupsService.GetAll().ToViewModel());
        }

        [HttpGet]
        [Route("{id}")]
        public IActionResult Details(long id)
        {
            var group = _groupsService.GetById(id);

            if (group == null)
            {
                return NotFound();
            }

            return View(group.ToViewModel());
        }

        [HttpPost]
        [Route("{id}")]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(long id, GroupViewModel model)
        {
            var group = _groupsService.Update(model.ToServiceModel());

            if (group == null)
            {
                return NotFound();
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        [Route("create")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Route("")]
        [ValidateAntiForgeryToken]
        public IActionResult CreateReally(GroupViewModel model)
        {
            _groupsService.Add(model.ToServiceModel());

            return RedirectToAction("Index");
        }
    }
}

gg.web/Views/Groups/Create.cshtml
@model GroupViewModel

<form asp-controller="Groups" asp-action="CreateReally" method="post">
    <label asp-for="Name">Name</label>
    <input asp-for="Name" />
    <button type="submit">Create</button>
</form>

gg.web/Views/Groups/Details.cshtml
@model GroupViewModel

<form asp-controller="Groups" asp-action="Edit" asp-route-id="@Model.Id" method="post">
    <label asp-for="Name">Name</label>
    <input asp-for="Name" />
    <button type="submit">Save</button>
</form>

gg.web/Views/Groups/Index.cshtml
@model IEnumerable<GroupViewModel>

<ul>
    @foreach (var group in Model)
    {
        <li>@group.Name <a asp-controller="Groups" asp-action="Details" asp-route-id="@group.Id">Edit</a></li>
    }
</ul>

<a asp-controller="Groups" asp-action="Create">Create</a>